apiVersion: v1
kind: Pod
metadata:
  name: mongodb-pvc-nfs
spec:
  containers:
  - image: mongo
    name: mongodb-pvc-nfs
    volumeMounts:
    - name: mongodb-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongodb-data
    persistentVolumeClaim:
      claimName: mongodb-pvc-nfs

