apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
  labels:
    run: kubia-rc
spec:
  replicas: 2
  selector:
    run: kubia-pod
  template:
    metadata:
      labels:
        run: kubia-pod
    spec:
      containers:
      - name: kubia
        image: k8mas.cluster.local/library/kubia:ch02
        ports:
        - containerPort: 8080
          protocol: TCP

