apiVersion: v1          #版本号为v1
kind: Namespace         #类型为Namespace
metadata:
  name: my-bks-k8sia
  labels:
    name: my-bks-k8sia-ns
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
  namespace: my-bks-k8sia
  labels:
    run: kubia-rc
spec:
  replicas: 3
  selector:
    run: kubia-pod
  template:
    metadata:
      labels:
        run: kubia-pod
    spec:
      containers:
      - name: kubia-pod
        image: k8fri.tianshdemo.org/library/kubia_ch02:v1
        ports:
        - containerPort: 8080
          protocol: TCP

