apiVersion: v1
kind: Service
metadata:
  name: kubia-svc-ch02
  namespace: my-bks-k8sia
spec:
  type: NodePort
  ports:
  - port: 30880
    # port是svc的端口，在集群上
    targetPort: 8080
    # targetPort是pod的端口
    nodePort: 30881
    # nodePort是node（集群节点）的端口
  selector:
    run: kubia-pod
