apiVersion: batch/v1
kind: Job      # 执行一次性的任务，本例运行了1个pod
metadata:
  name: batch-job
spec:
  template:
    metadata:
      labels:
        app: batch-job
    spec:
      restartPolicy: OnFailure   # 默认策略为Always，但Job只能使用OnFailure或Never。
      containers:
      - name: batch-job
        image: k8mas.cluster.local/library/batch-job:ch04
