apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: batch-job-every3min
spec:
  schedule: "*/3 * * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: batch-job-every3min
        spec:
          restartPolicy: OnFailure
          containers:
          - name: main
            image: k8s-mas.cluster.local/library/batch-job:latest
