apiVersion: apps/v1     # 格式：API组/实际版本
kind: ReplicaSet
metadata:
  name: kubia-rs
  namespace: my-bks-k8sia
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: k8fri.tianshdemo.org/library/kubia_ch02:v1
        ports:
        - containerPort: 8080
