apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc-ch04
spec:
  replicas: 3
  selector: 
    app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: k8fri.cluster.local/library/kubia:ch02
        ports:
        - containerPort: 8080
