apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rs-matchExp
spec:
  replicas: 3
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
         - kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: 192.168.56.138:5000/joelkhan/kubia-jsweb:v1
