apiVersion: v1
kind: Pod
metadata:
  name: kubia-unhealthy
  #namespace: my-bks-k8sia
spec:
  containers:
  - image: k8mas.cluster.local/library/kubia-unhealthy:ch04
    name: kubia-unhealthy
    ports:
    - containerPort: 8080
      protocol: TCP
    livenessProbe:
      httpGet:
        path: /
        port: 8080

