apiVersion: apps/v1     # 格式：API组/实际版本
kind: ReplicaSet
metadata:
  name: kubia-rs
  #namespace: my-bks-k8sia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: k8mas.cluster.local/library/kubia:ch02
        ports:
        - containerPort: 8080
