apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia-rs-matchExp
spec:
  replicas: 3
  selector:
    matchExpressions:   # 更富表达力的标签选择器
      - key: app
        operator: In
        values:
          - kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: k8mas.cluster.local/library/kubia:ch02
