apiVersion: v1
kind: Pod
metadata:
  name: kubia-po-liveness-ch04
  namespace: my-bks-k8sia
spec:
  containers:
  - image: k8fri.tianshdemo.org/library/kubia_unhealthy_ch04:latest
    name: kubia-liveness-ch04
    livenessProbe:
      httpGet:
        path: /
        port: 8080

