apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc-ch04
  #namespace: my-bks-k8sia
spec:
  replicas: 2
  #selector:    # 这是rc的选择器，它决定了所选的pod
    #app: kubia # 最佳实践是不指定选择器，k8会自动使用pod模板中的标签
  template:
    metadata:
      labels:    # 这是pod上的标签
        app: kubia
    spec:
      #nodeSelector:  # 这是节点选择器，可以决定pod落在哪类节点上
        #gpu: "true"
      containers:
      - image: k8mas.cluster.local/library/kubia:ch02
        name: kubia
        ports:
        - containerPort: 8080
