apiVersion: batch/v1
kind: Job
metadata:
  name: my-job
  namespace: my-bks-k8sia
spec:
  template:
    metadata:
      labels:
        app: my-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: main
        image: k8fri.tianshdemo.org/library/job_will_finish:v1
