apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ssd-monitor
  #namespace: my-bks-k8sia
spec:
  selector:
    matchLabels:  # 指出ds所监管的pod标签
      app: ssd-monitor
  template: # pod模板
    metadata:
      labels: # pod自己的标签
        app: ssd-monitor
    spec:
      nodeSelector: # pod将要选择的节点的标签
        disk: ssd
      containers:
      - name: ssd-monitor
        image: k8mas.cluster.local/library/ssd-monitor:ch04
