apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv-nfs
  labels:
    disk: ssd
spec:
  capacity: 
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  nfs: # nfs服务器
    path: /opt/nfs-dirs/mongodb-nfs-with-pv
    # 挂载位置
    server: 192.168.3.196
    #服务器地址
