kind: List
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-a
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: nfs
    nfs: # nfs服务器
      path: /opt/nfs-k8sia-sts1
      # 挂载位置
      server: 192.168.3.196
      #服务器地址
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-b
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: nfs
    nfs: # nfs服务器
      path: /opt/nfs-k8sia-sts2
      # 挂载位置
      server: 192.168.3.196
      #服务器地址
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: pv-c
  spec:
    capacity:
      storage: 1Mi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    storageClassName: nfs
    nfs: # nfs服务器
      path: /opt/nfs-k8sia-sts3
      # 挂载位置
      server: 192.168.3.196
      #服务器地址
