apiVersion: v1
kind: Pod
metadata:
  name: fortune-pod-args
  namespace: my-bks-k8sia
spec:
  containers:
  - image: k8fri.tianshdemo.org/library/fortune-args:v1
    args: ["2"]
    name: html-generator
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  - image: nginx:alpine
    name: web-server
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html
      readOnly: true
    ports:
    - containerPort: 80
      protocol: TCP
  volumes:
  - name: html
    emptyDir: {}

