apiVersion: v1
kind: Pod
metadata:
  name: kubia-po-manual
spec:
  containers:
  - image: k8mas.cluster.local/library/kubia:ch02
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
