apiVersion: v1
kind: Endpoints
metadata:
  name: external-service     # 这个名称必须和服务的名称匹配！
subsets:
  - addresses:
    - ip: 192.168.134.1     # 集群外部服务的IP，比如和node同网段的主机
    ports:
    - port: 33180       # 外部服务的端口
    
