apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc
spec:
  replicas: 2
  template:
    metadata:
      labels:    # 这是pod上的标签，rc依赖这个标签管理pod，svc依赖这个标签选择endpoints
        app: kubia
    spec:
      containers:
      - name: kubia
        image: k8s-mas.cluster.local/library/kubia:latest
        ports:
        - containerPort: 8080
