apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: kubia-ingress
  namespace: my-bks-k8sia
spec:
  ingressClassName: nginx
  rules:
  - host: kubia-ingress.example.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          serviceName: kubia-svc-ch05
          servicePort: 33080

