apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc-ch05
  namespace: my-bks-k8sia
spec:
  replicas: 3
  selector:    # 这是rc的选择器
    app: kubia
  template:
    metadata:
      labels:    # 这是pod上的标签
        app: kubia
    spec:
      containers:
      - name: kubia
        image: k8fri.tianshdemo.org/library/kubia_ch02:v1
        ports:
        - containerPort: 8080
