apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia-rc-dnsutils-pod
  labels:
    run: kubia-rc-dnsutils-pod
spec:
  replicas: 1
  selector:
    run: kubia-rc-dnsutils-pod
  template:
    metadata:
      labels:
        run: kubia-rc-dnsutils-pod
    spec:
      containers:
      - name: kubia-rc-dnsutils-pod
        image: k8fri.cluster.local/library/dnsutils:v1
