apiVersion: v1
kind: ReplicationController
metadata:
  name: kubia
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
      - name: kubia
        image: k8s-mas.cluster.local/library/kubia:latest
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:         # 定义了就绪探针
          exec:
            command:
            - ls
            - /var/ready
